boot.o: boot.S multiboot.h x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception.o: exception.c exception.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
page.o: page.c x86_desc.h types.h lib.h page.h
